##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://siarchive.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /avenu-archive 
# location of code, the full url to your github repository
source-code: https://siarchive.github.io/avenu-archive/ 

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Avenu Archive
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: University of Oregon School of Architecture and Allied Arts 
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Welcome to “avenu,” a journal produced by students at the University of Oregon’s School of Architecture and Allied Arts from 1972-1998. Originally printed as a monthly newspaper, the journal transitioned to a small booklet in the 90s before being disbanded in 1998. A few attempts have been made to revive the journal, including a blogspot in 2006 and a small zine in 2023. The journal preserves nearly three decades of student produced art, graphic design, poetry, and creative writing. Complementing these artistic endeavors are critical essays exploring the then-contemporary worlds of art and architecture criticism. The journal also offers a unique perspective on student cultures of the time,featuring critiques of campus construction projects, exposes on flawed registration and hiring practices, and reflections on the pedagogical practices of faculty. This archive facilitates easy exploration of the University's collection, organizing the archived journal by subject, editors, and topic. If a volume catches your eye, you can request to view it at the University of Oregon’s Special Collections, located on the second floor of the Knight Library. 
"
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Karianna Muller

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: METADATA

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png



##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "G-123XXXXXX"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
